/**
 * Authentic Russian Hotels Seed Data for RussiaBooking
 * Verified 4-star and 5-star properties across top Russian destinations
 * Tailored with amenities for Gulf and Middle Eastern travelers (Halal, Arabic, E-Visa, prayer mats, family suites)
 */

import { Hotel, HotelReview } from '../types';

export const SEED_HOTELS: Hotel[] = [
  {
    id: 'moscow-four-seasons',
    nameEn: 'Four Seasons Hotel Moscow',
    nameAr: 'فندق فور سيزونز موسكو',
    city: 'Moscow',
    cityAr: 'موسكو',
    country: 'Russia',
    addressEn: '2 Okhotny Ryad, Tverskoy, Moscow, 109012',
    addressAr: 'أوخوتني رياد 2، تفيرسكوي، موسكو',
    coordinates: { lat: 55.7569, lng: 37.6156 },
    stars: 5,
    rating: 9.6,
    reviewCount: 428,
    descriptionEn: 'An iconic luxury landmark overlooking the Red Square, Saint Basil’s Cathedral, and the Kremlin. Featuring opulent marble bathrooms, an expansive Amnis Spa, royal suites, and bespoke Arabic guest services.',
    descriptionAr: 'معلم فاخر استثنائي يطل مباشرة على الساحة الحمراء، كاتدرائية القديس باسيل والكرملين. يتميز بحمامات رخامية فخمة، وسبا أمنيس الشامل، وأجنحة ملكية مع خدمات استقبال باللغة العربية.',
    images: [
      { id: 'fs-1', url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80', isPrimary: true, captionEn: 'Hotel Exterior & Grand Entrance', captionAr: 'الواجهة الخارجية والمدخل الرئيسي' },
      { id: 'fs-2', url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80', captionEn: 'Kremlin View Luxury Suite', captionAr: 'جناح فاخر بإطلالة على الكرملين' },
      { id: 'fs-3', url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80', captionEn: 'Indoor Heated Swimming Pool & Spa', captionAr: 'مسبح داخلي دافئ وسبا ملكي' },
      { id: 'fs-4', url: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80', captionEn: 'Quadrum Fine Dining Restaurant', captionAr: 'مطعم كوادرم الفاخر' },
    ],
    amenities: ['wifi', 'halalCertified', 'spa', 'pool', 'airportShuttle', 'arabicTv', 'prayerRugs', 'visaAssistance', 'concierge247', 'fitness'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellationPolicyEn: 'Free cancellation until 48 hours prior to check-in. Late cancellations charged 1 night.',
      cancellationPolicyAr: 'إلغاء مجاني حتى 48 ساعة قبل موعد الوصول. الإلغاء المتأخر يخصم قيمة ليلة واحدة.',
      freeCancellationHours: 48,
      petFriendly: false,
      smokingAllowed: false,
      visaAssistanceProvided: true,
      halalCertifiedFood: true,
      prayerRugsAvailable: true,
    },
    minPriceRub: 38000,
    featured: true,
    active: true,
    createdAt: '2026-01-10T00:00:00Z',
    tagsEn: ['Red Square View', 'Ultra Luxury', 'Halal Available', 'Royal Spa'],
    tagsAr: ['إطلالة الساحة الحمراء', 'فخامة ملكية', 'طعام حلال متوفر', 'سبا متكامل'],
    nearbyLandmarksEn: [
      { name: 'Red Square', distance: '150 m' },
      { name: 'Kremlin & Armory Chamber', distance: '300 m' },
      { name: 'Bolshoi Theatre', distance: '400 m' },
      { name: 'GUM Luxury Mall', distance: '250 m' }
    ],
    nearbyLandmarksAr: [
      { name: 'الساحة الحمراء', distance: '150 م' },
      { name: 'الكرملين وغرفة الأسلحة', distance: '300 م' },
      { name: 'مسرح البولشوي الشهير', distance: '400 م' },
      { name: 'مركز غوم للتسوق الفاخر', distance: '250 م' }
    ],
    rooms: [
      {
        id: 'fs-deluxe-king',
        hotelId: 'moscow-four-seasons',
        nameEn: 'Deluxe City View Room',
        nameAr: 'غرفة ديلوكس بإطلالة على المدينة',
        descriptionEn: 'Spacious 48 sqm room with King bed, Russian art motifs, deep soaking marble tub, and city views.',
        descriptionAr: 'غرفة رحبة بمساحة 48 متر مربع بسرير كينغ، ولمسات فنية روسية، وحوض استحمام رخامي وإطلالة رائعة.',
        maxGuests: 2,
        maxAdults: 2,
        maxChildren: 1,
        bedTypeEn: '1 King Bed',
        bedTypeAr: 'سرير كينغ كبير',
        sizeSqm: 48,
        images: ['https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80'],
        amenities: ['wifi', 'marbleBathroom', 'nespresso', 'smartTv', 'arabicChannels'],
        rates: [
          {
            id: 'fs-deluxe-roomonly',
            roomId: 'fs-deluxe-king',
            nameEn: 'Room Only - Best Available Rate',
            nameAr: 'إقامة فقط - أفضل سعر متاح',
            pricePerNightRub: 38000,
            breakfastIncluded: false,
            refundable: true,
            freeCancellationDeadlineHours: 48,
            taxRatePercent: 10,
            availableQuantity: 5,
          },
          {
            id: 'fs-deluxe-bb',
            roomId: 'fs-deluxe-king',
            nameEn: 'Bed & Gourmet Halal Breakfast',
            nameAr: 'شامل بوفيه إفطار فاخر مع خيارات حلال',
            pricePerNightRub: 43500,
            breakfastIncluded: true,
            refundable: true,
            freeCancellationDeadlineHours: 48,
            taxRatePercent: 10,
            availableQuantity: 4,
          }
        ]
      },
      {
        id: 'fs-kremlin-suite',
        hotelId: 'moscow-four-seasons',
        nameEn: 'Grand Premier Suite with Red Square View',
        nameAr: 'جناح غراند بريمير بإطلالة مباشرة على الساحة الحمراء',
        descriptionEn: 'Ultra-luxurious 85 sqm suite featuring panoramic French windows facing the Kremlin, separate living room, and guest powder room.',
        descriptionAr: 'جناح فائق الفخامة بمساحة 85 متر مربع بنوافذ فرنسية بانورامية تواجه الكرملين، صالة معيشة منفصلة وحمام ضيوف إضافي.',
        maxGuests: 4,
        maxAdults: 3,
        maxChildren: 2,
        bedTypeEn: '1 King Bed + 1 Rollaway / Sofa bed',
        bedTypeAr: 'سرير كينغ + أريكة سريرية',
        sizeSqm: 85,
        images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80'],
        amenities: ['wifi', 'butlerService', 'vipLounge', 'marbleBathroom', 'arabicChannels'],
        rates: [
          {
            id: 'fs-suite-vip',
            roomId: 'fs-kremlin-suite',
            nameEn: 'VIP Suite Package (Breakfast + Airport Transfer)',
            nameAr: 'باقة كبار الشخصيات (شامل الإفطار وتوصيل المطار مجاناً)',
            pricePerNightRub: 68000,
            breakfastIncluded: true,
            refundable: true,
            freeCancellationDeadlineHours: 72,
            taxRatePercent: 10,
            availableQuantity: 2,
          }
        ]
      }
    ]
  },
  {
    id: 'moscow-the-carlton',
    nameEn: 'The Carlton, Moscow',
    nameAr: 'ذا كارلتون، موسكو',
    city: 'Moscow',
    cityAr: 'موسكو',
    country: 'Russia',
    addressEn: '3 Tverskaya Street, Moscow, 125009',
    addressAr: 'شارع تفيرسكايا 3، موسكو',
    coordinates: { lat: 55.7578, lng: 37.6133 },
    stars: 5,
    rating: 9.5,
    reviewCount: 380,
    descriptionEn: 'Located at the beginning of Tverskaya Street, steps from Red Square. Renowned for its world-famous O2 Lounge rooftop overlooking the Kremlin towers, crystal chandeliers, and Arabian royal hospitality standards.',
    descriptionAr: 'يقع في بداية شارع تفيرسكايا الراقي على بعد خطوات من الساحة الحمراء. يشتهر بروف توب O2 Lounge ذي الإطلالة الساحرة على أبراج الكرملين، وثريات الكريستال، وتوفير كافة متطلبات النزلاء العرب.',
    images: [
      { id: 'carlton-1', url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80', isPrimary: true, captionEn: 'Rooftop Panoramic Terrace', captionAr: 'تراس الروف توب البانورامي' },
      { id: 'carlton-2', url: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80', captionEn: 'Carlton Executive Bedroom', captionAr: 'غرفة كارلتون التنفيذية' },
      { id: 'carlton-3', url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80', captionEn: 'Luxury Indoor Thermal Pool', captionAr: 'المسبح الحراري الداخلي' },
    ],
    amenities: ['wifi', 'halalCertified', 'spa', 'pool', 'airportShuttle', 'arabicTv', 'prayerRugs', 'visaAssistance', 'fitness'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellationPolicyEn: 'Free cancellation up to 48 hours before check-in date.',
      cancellationPolicyAr: 'إلغاء مجاني حتى 48 ساعة قبل موعد تسجيل الوصول.',
      freeCancellationHours: 48,
      petFriendly: true,
      smokingAllowed: false,
      visaAssistanceProvided: true,
      halalCertifiedFood: true,
      prayerRugsAvailable: true,
    },
    minPriceRub: 32000,
    featured: true,
    active: true,
    createdAt: '2026-01-12T00:00:00Z',
    tagsEn: ['O2 Rooftop Lounge', '5-Star Luxury', 'Kremlin Proximity', 'Halal Menu'],
    tagsAr: ['روف توب O2 الشهير', 'فخامة 5 نجوم', 'قريب جداً من الكرملين', 'قائمة طعام حلال'],
    nearbyLandmarksEn: [
      { name: 'Red Square Entrance', distance: '200 m' },
      { name: 'GUM & Nikolskaya St', distance: '350 m' },
      { name: 'Tverskaya Shopping District', distance: '50 m' }
    ],
    nearbyLandmarksAr: [
      { name: 'مدخل الساحة الحمراء', distance: '200 م' },
      { name: 'مول غوم وشارع نيكولسكايا', distance: '350 م' },
      { name: 'منطقة تسوق تفيرسكايا', distance: '50 م' }
    ],
    rooms: [
      {
        id: 'carlton-superior',
        hotelId: 'moscow-the-carlton',
        nameEn: 'Superior King Room',
        nameAr: 'غرفة سوبيريور كينغ',
        descriptionEn: '42 sqm decorated in warm tones with classical dark polished wood and plush Portuguese marble bathroom.',
        descriptionAr: 'غرفة 42 متر مربع مصممة بدرجات دافئة وأخشاب كلاسيكية فاخرة وحمام رخامي برتغالي أنيق.',
        maxGuests: 2,
        maxAdults: 2,
        maxChildren: 1,
        bedTypeEn: '1 King Bed',
        bedTypeAr: '1 سرير كينغ',
        sizeSqm: 42,
        images: ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80'],
        amenities: ['wifi', 'marbleBathroom', 'nespresso', 'smartTv'],
        rates: [
          {
            id: 'carlton-rate-flexible',
            roomId: 'carlton-superior',
            nameEn: 'Flexible Rate (Free Cancellation)',
            nameAr: 'سعر مرن (إلغاء مجاني بالكامل)',
            pricePerNightRub: 32000,
            breakfastIncluded: false,
            refundable: true,
            freeCancellationDeadlineHours: 48,
            taxRatePercent: 10,
            availableQuantity: 6,
          },
          {
            id: 'carlton-rate-breakfast',
            roomId: 'carlton-superior',
            nameEn: 'Room + Carlton Buffet Breakfast',
            nameAr: 'غرفة + إفطار كارلتون الفاخر',
            pricePerNightRub: 37500,
            breakfastIncluded: true,
            refundable: true,
            freeCancellationDeadlineHours: 48,
            taxRatePercent: 10,
            availableQuantity: 4,
          }
        ]
      }
    ]
  },
  {
    id: 'moscow-radisson-collection',
    nameEn: 'Radisson Collection Hotel, Moscow',
    nameAr: 'فندق راديسون كوليكشن موسكو (أوتيل أوكرانيا)',
    city: 'Moscow',
    cityAr: 'موسكو',
    country: 'Russia',
    addressEn: '2/1 Kutuzovsky Prospekt, Moscow, 121248',
    addressAr: 'جادة كوتوزوفسكي 2/1، موسكو',
    coordinates: { lat: 55.7516, lng: 37.5654 },
    stars: 5,
    rating: 9.4,
    reviewCount: 512,
    descriptionEn: 'Housed in one of the legendary Seven Sisters Stalin skyscrapers on the Moskva River. Features its own fleet of luxury ice-breaker river yachts, 50-meter Olympic pool, and 16 top-tier international restaurants.',
    descriptionAr: 'يقع في إحدى ناطحات السحاب السبع الشهيرة تاريخياً على ضفاف نهر موسكفا. يمتلك أسطوله الخاص من اليخوت النهرية الفاخرة، ومسبح أولمبي بطول 50 متراً، و16 مطعماً عالمياً راقياً.',
    images: [
      { id: 'rad-1', url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80', isPrimary: true, captionEn: 'Historic Skyscraper on River', captionAr: 'البرج التاريخي على ضفاف النهر' },
      { id: 'rad-2', url: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80', captionEn: 'River View Deluxe Room', captionAr: 'غرفة ديلوكس بإطلالة على النهر' },
    ],
    amenities: ['wifi', 'halalCertified', 'spa', 'pool', 'airportShuttle', 'arabicTv', 'prayerRugs', 'visaAssistance', 'fitness'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellationPolicyEn: 'Free cancellation up to 24 hours prior to arrival.',
      cancellationPolicyAr: 'إلغاء مجاني حتى 24 ساعة قبل موعد الوصول.',
      freeCancellationHours: 24,
      petFriendly: true,
      smokingAllowed: false,
      visaAssistanceProvided: true,
      halalCertifiedFood: true,
      prayerRugsAvailable: true,
    },
    minPriceRub: 21000,
    featured: true,
    active: true,
    createdAt: '2026-01-15T00:00:00Z',
    tagsEn: ['Historic Skyscraper', 'River Cruise Yacht', 'Olympic Pool', 'Kutuzovsky Avenue'],
    tagsAr: ['برج ستالين التاريخي', 'يخوت نهرية خاصة', 'مسبح أولمبي 50م', 'شارع كوتوزوفسكي'],
    nearbyLandmarksEn: [
      { name: 'Moscow City Business Towers', distance: '1.2 km' },
      { name: 'Arbat Pedestrian Street', distance: '1.5 km' },
      { name: 'Radisson River Yacht Pier', distance: '50 m' }
    ],
    nearbyLandmarksAr: [
      { name: 'أبراج موسكو سيتي الحديثة', distance: '1.2 كم' },
      { name: 'شارع أربات السياحي للمشاة', distance: '1.5 كم' },
      { name: 'مرسى يخوت راديسون النهرية', distance: '50 م' }
    ],
    rooms: [
      {
        id: 'rad-collection-deluxe',
        hotelId: 'moscow-radisson-collection',
        nameEn: 'Collection River View Room',
        nameAr: 'غرفة كوليكشن بإطلالة على نهر موسكفا',
        descriptionEn: '38 sqm stylish room with high ceilings, river views, and premium Italian bedding.',
        descriptionAr: 'غرفة أنيقة 38 متر مربع بأسقف مرتفعة وإطلالة نهرية ساحرة وأسرّة إيطالية فاخرة.',
        maxGuests: 2,
        maxAdults: 2,
        maxChildren: 1,
        bedTypeEn: '1 King Bed or 2 Twin Beds',
        bedTypeAr: 'سرير كينغ أو سريرين منفصلين',
        sizeSqm: 38,
        images: ['https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80'],
        amenities: ['wifi', 'smartTv', 'arabicChannels', 'miniBar'],
        rates: [
          {
            id: 'rad-rate-standard',
            roomId: 'rad-collection-deluxe',
            nameEn: 'Standard Room Rate',
            nameAr: 'السعر الأساسي القياسي',
            pricePerNightRub: 21000,
            breakfastIncluded: false,
            refundable: true,
            freeCancellationDeadlineHours: 24,
            taxRatePercent: 10,
            availableQuantity: 8,
          },
          {
            id: 'rad-rate-yacht',
            roomId: 'rad-collection-deluxe',
            nameEn: 'Room + River Yacht Cruise Ticket + Breakfast',
            nameAr: 'غرفة + تذكرة يخت نهري + إفطار شامل',
            pricePerNightRub: 27500,
            breakfastIncluded: true,
            refundable: true,
            freeCancellationDeadlineHours: 24,
            taxRatePercent: 10,
            availableQuantity: 5,
          }
        ]
      }
    ]
  },
  {
    id: 'spb-belmond-grand-europe',
    nameEn: 'Belmond Grand Hotel Europe, Saint Petersburg',
    nameAr: 'فندق بلموند غراند أوروبا، سانت بطرسبرغ',
    city: 'Saint Petersburg',
    cityAr: 'سانت بطرسبرغ',
    country: 'Russia',
    addressEn: '1/7 Mikhailovskaya Ulitsa, Saint Petersburg, 191186',
    addressAr: 'شارع ميخايلوفسكايا 1/7، سانت بطرسبرغ',
    coordinates: { lat: 59.9360, lng: 30.3323 },
    stars: 5,
    rating: 9.7,
    reviewCount: 395,
    descriptionEn: 'A 145-year-old cultural jewel on Nevsky Prospekt. Celebrated for its Art Nouveau stained-glass restaurant, caviar bar, ballet tours, and imperial aristocratic suites.',
    descriptionAr: 'جوهرة كلاسيكية تمتد لأكثر من 145 عاماً على جادة نيفسكي الشهيرة. يتميز بمطعمه المصنوع من الزجاج المعشق على طراز الآرت نوفو، وأجنحته الإمبراطورية الأنيقة.',
    images: [
      { id: 'bel-1', url: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80', isPrimary: true, captionEn: 'Historic Facade & Grand Hall', captionAr: 'الواجهة التاريخية والبهو الملكي' },
      { id: 'bel-2', url: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80', captionEn: 'Imperial Suite Living Room', captionAr: 'صالة الجناح الإمبراطوري' },
    ],
    amenities: ['wifi', 'halalCertified', 'spa', 'airportShuttle', 'arabicTv', 'prayerRugs', 'visaAssistance', 'concierge247'],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '12:00',
      cancellationPolicyEn: 'Free cancellation up to 48 hours before check-in.',
      cancellationPolicyAr: 'إلغاء مجاني حتى 48 ساعة قبل موعد تسجيل الوصول.',
      freeCancellationHours: 48,
      petFriendly: true,
      smokingAllowed: false,
      visaAssistanceProvided: true,
      halalCertifiedFood: true,
      prayerRugsAvailable: true,
    },
    minPriceRub: 29000,
    featured: true,
    active: true,
    createdAt: '2026-01-18T00:00:00Z',
    tagsEn: ['Nevsky Prospekt', 'Historic Palace', 'Art Nouveau', 'Hermitage Proximity'],
    tagsAr: ['جادة نيفسكي بروسبكت', 'قصر تاريخي', 'طراز آرت نوفو', 'قريب من متحف الأرميتاج'],
    nearbyLandmarksEn: [
      { name: 'State Hermitage Museum', distance: '800 m' },
      { name: 'Church of the Savior on Spilled Blood', distance: '450 m' },
      { name: 'Nevsky Prospekt Metro', distance: '100 m' }
    ],
    nearbyLandmarksAr: [
      { name: 'متحف الأرميتاج وقصر الشتاء', distance: '800 م' },
      { name: 'كنيسة المخلص على الدم المراق', distance: '450 م' },
      { name: 'محطة مترو نيفسكي بروسبكت', distance: '100 م' }
    ],
    rooms: [
      {
        id: 'bel-classic',
        hotelId: 'spb-belmond-grand-europe',
        nameEn: 'Classic Heritage Room',
        nameAr: 'غرفة التراث الكلاسيكية',
        descriptionEn: '32 sqm room with authentic imperial Russian decor, high stucco ceilings, and Italian marble bathroom.',
        descriptionAr: 'غرفة بمساحة 32 متر مربع بديكورات روسية إمبراطورية أصلية، وأسقف مزخرفة عالية وحمام رخامي.',
        maxGuests: 2,
        maxAdults: 2,
        maxChildren: 1,
        bedTypeEn: '1 King or 2 Twins',
        bedTypeAr: 'سرير كينغ أو سريرين',
        sizeSqm: 32,
        images: ['https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80'],
        amenities: ['wifi', 'marbleBathroom', 'nespresso', 'smartTv'],
        rates: [
          {
            id: 'bel-rate-bed',
            roomId: 'bel-classic',
            nameEn: 'Best Available Rate',
            nameAr: 'أفضل سعر متاح مع إلغاء مجاني',
            pricePerNightRub: 29000,
            breakfastIncluded: false,
            refundable: true,
            freeCancellationDeadlineHours: 48,
            taxRatePercent: 10,
            availableQuantity: 4,
          },
          {
            id: 'bel-rate-breakfast',
            roomId: 'bel-classic',
            nameEn: 'Heritage Room + Grand Breakfast',
            nameAr: 'غرفة + بوفيه إفطار غراند الأوروبي الشهير',
            pricePerNightRub: 34500,
            breakfastIncluded: true,
            refundable: true,
            freeCancellationDeadlineHours: 48,
            taxRatePercent: 10,
            availableQuantity: 3,
          }
        ]
      }
    ]
  },
  {
    id: 'sochi-radisson-paradise',
    nameEn: 'Radisson Collection Paradise Resort & Spa Sochi',
    nameAr: 'منتجع وسبا راديسون كوليكشن بارادايس سوتشي',
    city: 'Sochi',
    cityAr: 'سوتشي',
    country: 'Russia',
    addressEn: '65 Let Pobedy St 50, Imeretinskaya Lowland, Sochi, 354340',
    addressAr: 'شارع 65 ليت بوبيدي 50، إيميريتينسكي، سوتشي',
    coordinates: { lat: 43.3934, lng: 39.9768 },
    stars: 5,
    rating: 9.3,
    reviewCount: 310,
    descriptionEn: 'Luxury beachfront resort on the subtropical Black Sea coast with palm gardens, 2,500 sqm thermal spa complex, private sand-pebble beach, and mountain excursion desks.',
    descriptionAr: 'منتجع ساحلي فاخر على شاطئ البحر الأسود الاستوائي بحدائق النخيل، وسبا حراري بمساحة 2500 م2، وشاطئ خاص، وإمكانية حجز رحلات جبلية ممتعة.',
    images: [
      { id: 'sochi-1', url: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1200&q=80', isPrimary: true, captionEn: 'Resort Beachfront & Lagoon Pools', captionAr: 'شاطئ المنتجع والمسابح المحاطة بالنخيل' },
      { id: 'sochi-2', url: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80', captionEn: 'Sea View Balcony Room', captionAr: 'غرفة بشرفة مطلة على البحر الأسود' },
    ],
    amenities: ['wifi', 'halalCertified', 'spa', 'pool', 'airportShuttle', 'arabicTv', 'prayerRugs', 'visaAssistance', 'fitness'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellationPolicyEn: 'Free cancellation up to 48 hours prior to arrival.',
      cancellationPolicyAr: 'إلغاء مجاني حتى 48 ساعة قبل الوصول.',
      freeCancellationHours: 48,
      petFriendly: false,
      smokingAllowed: false,
      visaAssistanceProvided: true,
      halalCertifiedFood: true,
      prayerRugsAvailable: true,
    },
    minPriceRub: 22000,
    featured: true,
    active: true,
    createdAt: '2026-01-20T00:00:00Z',
    tagsEn: ['Black Sea Beachfront', 'Thermal Spa 2500sqm', 'Olympic Park', 'Family Resort'],
    tagsAr: ['شاطئ البحر الأسود المباشر', 'سبا حراري ضخم', 'قريب من الحديقة الأولمبية', 'منتجع عائلي متكامل'],
    nearbyLandmarksEn: [
      { name: 'Olympic Park & F1 Track', distance: '1.5 km' },
      { name: 'Sochi International Airport (AER)', distance: '8 km' },
      { name: 'Rosa Khutor Ski Mountain', distance: '38 km' }
    ],
    nearbyLandmarksAr: [
      { name: 'الحديقة الأولمبية وحلبة فورمولا 1', distance: '1.5 كم' },
      { name: 'مطار سوتشي الدولي (AER)', distance: '8 كم' },
      { name: 'منتجع روزا خوتور الجبلي للتزلج', distance: '38 كم' }
    ],
    rooms: [
      {
        id: 'sochi-seaview',
        hotelId: 'sochi-radisson-paradise',
        nameEn: 'Superior Sea View Room with Balcony',
        nameAr: 'غرفة سوبيريور بإطلالة على البحر وشرفة خاصة',
        descriptionEn: '36 sqm airy room with floor-to-ceiling glass doors opening to private balcony overlooking the Black Sea.',
        descriptionAr: 'غرفة مشرقة بمساحة 36 متر مربع مع أبواب زجاجية ممتدة وشرفة خاصة مطلة على مياه البحر الأسود.',
        maxGuests: 3,
        maxAdults: 2,
        maxChildren: 1,
        bedTypeEn: '1 King Bed + Daybed',
        bedTypeAr: 'سرير كينغ + أريكة استرخاء',
        sizeSqm: 36,
        images: ['https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&q=80'],
        amenities: ['wifi', 'seaViewBalcony', 'smartTv', 'nespresso'],
        rates: [
          {
            id: 'sochi-rate-standard',
            roomId: 'sochi-seaview',
            nameEn: 'Room Only (Free Cancellation)',
            nameAr: 'سعر الغرفة فقط مع إلغاء مجاني',
            pricePerNightRub: 22000,
            breakfastIncluded: false,
            refundable: true,
            freeCancellationDeadlineHours: 48,
            taxRatePercent: 10,
            availableQuantity: 7,
          },
          {
            id: 'sochi-rate-allinclusive-breakfast',
            roomId: 'sochi-seaview',
            nameEn: 'Bed & International Breakfast Buffet',
            nameAr: 'شامل بوفيه إفطار عالمي غني مع أطباق ساخنة',
            pricePerNightRub: 26500,
            breakfastIncluded: true,
            refundable: true,
            freeCancellationDeadlineHours: 48,
            taxRatePercent: 10,
            availableQuantity: 5,
          }
        ]
      }
    ]
  },
  {
    id: 'kazan-palace-tasigo',
    nameEn: 'Kazan Palace by Tasigo',
    nameAr: 'فندق قازان بالاس باي تاسيغو',
    city: 'Kazan',
    cityAr: 'قازان',
    country: 'Russia',
    addressEn: '56 Kalinina Street, Kazan, 420043',
    addressAr: 'شارع كالينا 56، قازان، تتارستان',
    coordinates: { lat: 55.7794, lng: 49.1432 },
    stars: 5,
    rating: 9.8,
    reviewCount: 284,
    descriptionEn: 'The pride of Tatarstan hospitality. A magnificent converted historic palace featuring 100% certified Halal dining, GO SPA with traditional Turkish hammam, Arabic speaking guest relations, and seamless E-Visa registration.',
    descriptionAr: 'فخر الضيافة في عاصمة تتارستان. قصر تاريخي مُرمم بأعلى المعايير، يضم مطابخ حلال 100% معتمدة، وسبا تركي وحمام عثماني أصيل، وموظفين يتحدثون العربية وتأكيد رسمي فوري للتأشيرة.',
    images: [
      { id: 'kaz-1', url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80', isPrimary: true, captionEn: 'Kazan Palace Grand Facade', captionAr: 'الواجهة التاريخية الفخمة لقصر قازان' },
      { id: 'kaz-2', url: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1200&q=80', captionEn: 'Palace Suite with Turkish Hammam', captionAr: 'جناح القصر مع حمام رخامي فاخر' },
    ],
    amenities: ['wifi', 'halalCertified', 'spa', 'pool', 'airportShuttle', 'arabicTv', 'prayerRugs', 'visaAssistance', 'fitness'],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '12:00',
      cancellationPolicyEn: 'Free cancellation up to 24 hours prior to check-in.',
      cancellationPolicyAr: 'إلغاء مجاني حتى 24 ساعة قبل موعد الوصول.',
      freeCancellationHours: 24,
      petFriendly: false,
      smokingAllowed: false,
      visaAssistanceProvided: true,
      halalCertifiedFood: true,
      prayerRugsAvailable: true,
    },
    minPriceRub: 18500,
    featured: true,
    active: true,
    createdAt: '2026-01-22T00:00:00Z',
    tagsEn: ['100% Halal Certified', 'GO Spa & Turkish Hammam', 'Tatar Cultural Luxury', 'Kazan Kremlin Nearby'],
    tagsAr: ['طعام حلال 100% معتمد', 'سبا وحمام تركي عريق', 'أجواء إسلامية وتترية راقية', 'قريب من قلعة قازان'],
    nearbyLandmarksEn: [
      { name: 'Kazan Kremlin & Kul Sharif Mosque', distance: '2.5 km' },
      { name: 'Bauman Pedestrian Street', distance: '1.2 km' },
      { name: 'Kaban Lake Waterfront Promenade', distance: '800 m' }
    ],
    nearbyLandmarksAr: [
      { name: 'كرملين قازان وجامع قول شريف الشهير', distance: '2.5 كم' },
      { name: 'شارع باومان التراثي للمشاة', distance: '1.2 كم' },
      { name: 'كورنيش بحيرة كابان الساحر', distance: '800 م' }
    ],
    rooms: [
      {
        id: 'kaz-palace-king',
        hotelId: 'kazan-palace-tasigo',
        nameEn: 'Grand Palace King Room',
        nameAr: 'غرفة غراند بالاس كينغ',
        descriptionEn: '45 sqm room with high ceilings, plush bespoke furnishings, prayer rug, and certified halal in-room refreshments.',
        descriptionAr: 'غرفة واسعة بمساحة 45 متر مربع بأسقف عالية، وسجادة صلاة، ومشروبات حلال معتمدة في الغرفة.',
        maxGuests: 2,
        maxAdults: 2,
        maxChildren: 1,
        bedTypeEn: '1 King Bed',
        bedTypeAr: 'سرير كينغ فاخر',
        sizeSqm: 45,
        images: ['https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80'],
        amenities: ['wifi', 'halalCertified', 'prayerRugs', 'nespresso', 'smartTv'],
        rates: [
          {
            id: 'kaz-rate-bb',
            roomId: 'kaz-palace-king',
            nameEn: 'Halal Certified Gourmet Breakfast Included',
            nameAr: 'شامل بوفيه إفطار حلال معتمد ومتنوع',
            pricePerNightRub: 18500,
            breakfastIncluded: true,
            refundable: true,
            freeCancellationDeadlineHours: 24,
            taxRatePercent: 10,
            availableQuantity: 5,
          }
        ]
      }
    ]
  },
  {
    id: 'murmansk-azimut-aurora',
    nameEn: 'Azimut Hotel Murmansk',
    nameAr: 'فندق أزيموت مورمانسك (شمال الدائرة القطبية)',
    city: 'Murmansk',
    cityAr: 'مورمانسك',
    country: 'Russia',
    addressEn: 'Lenina Prospekt 82, Murmansk, 183038',
    addressAr: 'جادة لينين 82، ساحة خمسة أركان، مورمانسك',
    coordinates: { lat: 68.9712, lng: 33.0766 },
    stars: 4,
    rating: 9.0,
    reviewCount: 220,
    descriptionEn: 'The northernmost high-rise hotel in the world. Located on the central Five Corners Square, the ideal headquarters for chasing the Aurora Borealis (Northern Lights) and Arctic snow experiences.',
    descriptionAr: 'أعلى وأفخم فندق شمال الدائرة القطبية في العالم. يقع في ساحة خمسة أركان المركزية، ويمثل المقر المثالي للمسافرين الراغبين بمشاهدة الشفق القطبي ورحلات السفاري الثلجية.',
    images: [
      { id: 'mur-1', url: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=1200&q=80', isPrimary: true, captionEn: 'Aurora Borealis over Murmansk', captionAr: 'أضواء الشفق القطبي فوق مورمانسك' },
      { id: 'mur-2', url: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80', captionEn: 'Cozy Nordic Standard Room', captionAr: 'غرفة مريحة دافئة على الطراز الشمالي' },
    ],
    amenities: ['wifi', 'halalCertified', 'airportShuttle', 'visaAssistance', 'concierge247', 'fitness'],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '12:00',
      cancellationPolicyEn: 'Free cancellation up to 48 hours before check-in.',
      cancellationPolicyAr: 'إلغاء مجاني حتى 48 ساعة قبل موعد الوصول.',
      freeCancellationHours: 48,
      petFriendly: true,
      smokingAllowed: false,
      visaAssistanceProvided: true,
      halalCertifiedFood: true,
      prayerRugsAvailable: true,
    },
    minPriceRub: 14500,
    featured: false,
    active: true,
    createdAt: '2026-01-25T00:00:00Z',
    tagsEn: ['Northern Lights Tours', 'Arctic Experience', 'Five Corners Square', 'Warm Suites'],
    tagsAr: ['رحلات الشفق القطبي', 'مغامرة القطب الشمالي', 'ساحة خمسة أركان', 'أجنحة دافئة'],
    nearbyLandmarksEn: [
      { name: 'Five Corners Central Square', distance: '50 m' },
      { name: 'Nuclear Icebreaker Lenin Museum', distance: '1.4 km' },
      { name: 'Aurora Chasing Starting Point', distance: 'On Site' }
    ],
    nearbyLandmarksAr: [
      { name: 'ساحة خمسة أركان المركزية', distance: '50 م' },
      { name: 'متحف كاسحة الجليد النووية لينين', distance: '1.4 كم' },
      { name: 'نقطة انطلاق جولات الشفق القطبي', distance: 'من الفندق' }
    ],
    rooms: [
      {
        id: 'mur-standard',
        hotelId: 'murmansk-azimut-aurora',
        nameEn: 'Standard Warm Nordic Room',
        nameAr: 'غرفة نورديك دافئة قياسية',
        descriptionEn: '26 sqm cozy, temperature-controlled room with high-speed Wi-Fi, heated bathroom floors, and panoramic view.',
        descriptionAr: 'غرفة دافئة ومكيفة حرارياً 26 متر مربع مع أرضية حمام مدفأة وإطلالة بانورامية على أفق المدينة القطبي.',
        maxGuests: 2,
        maxAdults: 2,
        maxChildren: 1,
        bedTypeEn: '1 Double or 2 Twin Beds',
        bedTypeAr: 'سرير مزدوج أو سريرين',
        sizeSqm: 26,
        images: ['https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80'],
        amenities: ['wifi', 'heatedFloors', 'smartTv'],
        rates: [
          {
            id: 'mur-rate-std',
            roomId: 'mur-standard',
            nameEn: 'Standard Rate + Breakfast',
            nameAr: 'السعر القياسي مع الإفطار الساخن',
            pricePerNightRub: 14500,
            breakfastIncluded: true,
            refundable: true,
            freeCancellationDeadlineHours: 48,
            taxRatePercent: 10,
            availableQuantity: 6,
          }
        ]
      }
    ]
  }
];

export const SEED_REVIEWS: HotelReview[] = [
  {
    id: 'rev-1',
    hotelId: 'moscow-four-seasons',
    bookingId: 'RB-2026-101',
    userId: 'user-sa-1',
    userName: 'سلطان القحطاني',
    userCountry: 'Saudi Arabia 🇸🇦',
    rating: 10,
    subRatings: { cleanliness: 10, location: 10, service: 10, value: 9.5 },
    title: 'تجربة ملكية استثنائية في قلب موسكو',
    comment: 'الإقامة كانت تفوق الخيال! إطلالة الجناح على الساحة الحمراء والكرملين ساحرة. الفندق وفر لنا سجادة صلاة وقائمة إفطار حلال رائعة وموظف استقبال يتحدث العربية ساعدنا في كل الجولات. الدفع بمدى كان سلساً جداً.',
    travelerType: 'family',
    verifiedBooking: true,
    createdAt: '2026-02-14T10:00:00Z',
  },
  {
    id: 'rev-2',
    hotelId: 'moscow-the-carlton',
    bookingId: 'RB-2026-102',
    userId: 'user-uae-1',
    userName: 'Mohammed Al Mazrouei',
    userCountry: 'United Arab Emirates 🇦🇪',
    rating: 9.8,
    subRatings: { cleanliness: 9.8, location: 10, service: 9.8, value: 9.5 },
    title: 'Unforgettable rooftop and top-tier hospitality',
    comment: 'The O2 Lounge rooftop views are unparalleled. Very courteous staff, prompt visa voucher issuance which made the Russian E-Visa process smooth. Highly recommend for GCC travelers.',
    travelerType: 'couple',
    verifiedBooking: true,
    createdAt: '2026-02-18T14:30:00Z',
  },
  {
    id: 'rev-3',
    hotelId: 'kazan-palace-tasigo',
    bookingId: 'RB-2026-103',
    userId: 'user-kw-1',
    userName: 'فهد المطيري',
    userCountry: 'Kuwait 🇰🇼',
    rating: 10,
    subRatings: { cleanliness: 10, location: 9.8, service: 10, value: 10 },
    title: 'أفضل وجهة حلال للعائلات الخليجية',
    comment: 'قازان مدينة جميلة جداً وشعبها ودود للغاية، وفندق تاسيغو قصر فخم بكل معنى الكلمة. كل الطعام حلال ومعتمد، والسبا التركي مريح جداً بعد يوم من زيارة المعالم التاريخية.',
    travelerType: 'family',
    verifiedBooking: true,
    createdAt: '2026-02-22T09:15:00Z',
  }
];
